export default InstrumentsList = [
  "Afoxé",
  "Agogô",
  "Agung",
  "Angklung",
  "Babendil",
  "Bak",
  "Bamileke log drum",
  "Balafon",
  "Batá drum",
  "Cabasa",
  "Cajón",
  "Carillon",
  "Castanets",
  "Caxirola",
  "Caxixi",
  "Chácaras",
  "Clapstick",
  "Claves",
  "Cowbell",
  "Crotales",
  "Cymbal",
  "Ferrinho",
  "Flexatone",
  "Octa-Vibraphone",
  "Gandingan",
  "Ghatam",
  "Glockenspiel",
  "Gong",
  "Güiro",
  "Handpan",
  "Hang",
  "Kayamb",
  "Kemanak",
  "Khartal",
  "Kouxian",
  "Kulintang",
  "Maraca",
  "Marimba",
  "Mbira",
  "Pate",
  "Shekere",
  "Slit drum",
  "Spoon",
  "Steelpan",
  "Tambourine",
  "Teponaztli",
  "Triangle",
  "Trash Tube",
  "Txalaparta",
  "Vibraphone",
  "Vibraslap",
  "Washboard",
  "Wood block",
  "Wooden fish",
  "Xylophone",
  "Zill",
  "buleador",
  "primo",
  "repicador",
  "subidor",
  "chico",
  "repique",
  "piano",
  "Uruttu chenda",
  "Veekku chenda",
  "Acchan chenda",
  "ricardo",
  "requinto",
  "quinto",
  "conga",
  "tumba",
  "supertumba",
  "Dohol",
  "Tapan, Topan, Tupan",
  "Tabl",
  "Toba, Towla",
  "Tof",
  "Ishakwe",
  "Inyahura",
  "Igihumurizo",
  "Celesta",
  "Crystallophone",
  "Glasschord",
  "Glass harmonica",
  "Hydraulophone",
  "Plasmaphone",
  "Pyrophone",
  "Quintephone",
  "Asadullah",
  "Sea organ",
  "Shishiodoshi",
  "Suikinkutsu",
  "Wobble board",
  "Buttonaccordion",
  "Cajun accordion",
  "Chromatic button accordion",
  "Diatonic button accordion",
  "Free bass accordion",
  "Piano accordion",
  "Schrammelaccordion",
  "SteirischeHarmonika",
  "Contrabassoon/doublebassoon",
  "Tenoroon",
  "Chromatic bombarde",
  "Alto clarinet",
  "Bass clarinet",
  "Basset clarinet",
  "Bassethorn",
  "Clarinette d'amour",
  "Contra-alto clarinet",
  "Contrabassclarinet",
  "Piccolo clarinet",
  "Sopranino clarinet",
  "Soprano clarinet",
  "Octocontra-alto clarinet",
  "Octocontrabass clarinet",
  "clarinet",
  "Chemnitzer concertina",
  "Soprano cornet",
  "Guanzi",
  "Houguan",
  "Chromaticharmonica",
  "Diatonicharmonica",
  "Tremoloharmonica",
  "Orchestral harmonica",
  "ChenGong harmonica",
  "Piccoloheckelphone",
  "Terz heckelphone",
  "Bass/Baritone oboe",
  "Contrabass oboe",
  "Cor anglais/English horn",
  "Oboe d'amore",
  "Oboe da caccia",
  "Piccolo oboe/Oboemusette",
  "Transverse ocarina",
  "Pendant ocarina",
  "Inline ocarina",
  "Multi chambered ocarina",
  "Keyed ocarina",
  "Slide ocarina",
  "Garklein",
  "Sopranino",
  "Descant",
  "Treble or alto",
  "Tenor",
  "Bass",
  "Great bass",
  "Contra bass",
  "Subcontra bass",
  "Sub-subcontrabass",
  "Venova",
  "Alto sackbut",
  "Tenor sackbut",
  "Bass sackbut",
  "Double bass sackbut",
  "Altosarrusophone",
  "Baritonesarrusophone",
  "Basssarrusophone",
  "Contrabass sarrusophone",
  "Sopraninosarrusophone",
  "Sopranosarrusophone",
  "Tenorsarrusophone",
  "Alto saxophone",
  "Baritonesaxophone",
  "Bass saxophone",
  "C melodysaxophone",
  "C Soprano saxophone",
  "Contrabasssaxophone",
  "Mezzo-soprano saxophone",
  "Sopraninosaxophone",
  "Sopranosaxophone",
  "Soprillo",
  "Subcontrabass saxophone",
  "Tenor saxophone",
  "Tubax",
  "Venova",
  "Xaphoon",
  "Medieval slide trumpet",
  "Renaissance slide trumpet",
  "Baroque slide trumpet",
  "Jazz flute",
  "Swanee whistle",
  "Laba",
  "Haidi",
  "Sopranino trombone",
  "Soprano trombone",
  "Alto trombone",
  "Tenor trombone",
  "Basstrombone",
  "Contrabass trombone",
  "Valve trombone",
  "Soprano trumpet",
  "Bass trumpet",
  "Baroque trumpet",
  "Bass trumpet",
  "Rotary valve trumpet",
  "Bass tuba",
  "Contrabass tuba",
  "Subcontrabasstuba",
  "Flute",
  "Alto flute",
  "Bass flute",
  "Contra-altoflute",
  "Contrabassflute",
  "Subcontrabass flute",
  "Double contrabass flute",
  "Hyperbass flute",
  "Pea whistle",
  "Steam whistle",
  "Train whistle",
  "Surnay",
  "Banjo cello",
  "Bass banjo",
  "Five-stringed banjo",
  "Four-stringed banjo",
  "Six-stringed banjo",
  "Tenor banjo",
  "Zither banjo",
  "Bluegrass banjo",
  "Plectrum banjo",
  "Cello da spalla",
  "Electric cello",
  "Charango",
  "Charangón",
  "Hualaycho",
  "Ronroco",
  "Hatun charango",
  "Chillador",
  "Ayacucho",
  "Bajo charango",
  "Chango",
  "Charango mediano",
  "KhonKhota",
  "Moquegua",
  "Pampeno",
  "Shreiker",
  "Sonko",
  "Vallegrandino",
  "Electric cymbalum",
  "mandolinos de concheros or mandolina conchera",
  "vihuelas de concheros or vihuela conchera",
  "guitarras de concheros or guitarra conchera",
  "Five-string double bass",
  "Acoustic guitar",
  "Acousticbass guitar",
  "Acoustic-electric guitar",
  "Archtop guitar",
  "Baritone guitar",
  "Baroque guitar",
  "Bass guitar",
  "Bahian guitar",
  "Brahms guitar",
  "Chitarrabattente",
  "Cigar boxguitar",
  "Classicalguitar",
  "Consolesteel guitar",
  "Electric guitar",
  "English guitar",
  "Fretless guitar",
  "Lyre-guitar",
  "Extended-range guitar",
  "Flamenco guitar",
  "Fusetar",
  "Guitarra quinta huapanguera",
  "Guitarsynthesizer",
  "Guitarrón (chileno)",
  "Guitarrón (mexicano)",
  "Guitarrón (uruguayo)",
  "Gut-stringed guitar",
  "Lap steelguitar",
  "Multi-neckguitar",
  "Octave guitar",
  "Parlor guitar",
  "Pedal steelguitar",
  "Resophonic guitar",
  "Romantic guitar",
  "Russian guitar",
  "Selmer guitar",
  "Semi-acoustic guitar",
  "Slide guitar",
  "Silent guitar",
  "Steel guitar",
  "Steel-string acoustic guitar",
  "Tenor guitar",
  "Terz guitar",
  "Yotar",
  "Alto guitar",
  "Seven-string guitar",
  "Eight-string guitar",
  "Nine-string guitar",
  "Ten-string guitar",
  "Eleven-string alto guitar",
  "Twelve-string guitar",
  "Dobro",
  "Double-neck guitar",
  "Triple-neck guitar",
  "Quadruple-neck guitar",
  "Five-neck guitar",
  "Six-neck guitar",
  "Seven-neck guitar",
  "Eight-neck guitarRock Ock",
  "Twelve-neck guitar",
  "Rock Ock",
  "Electric harp",
  "Mandolin-banjo",
  "Mandocello",
  "Mandola",
  "Bluegrass mandolin",
  "Electric mandolin",
  "Octave mandolin",
  "Resonator mandolin",
  "Electric piano",
  "Fortepiano",
  "Pedal piano",
  "Gaoyinruan",
  "Xiaoruan",
  "Zhongruan",
  "Daruan",
  "Diyinruan",
  "Tres Cubano",
  "Tres Puerto Rico",
  "Concert ukulele",
  "Electricukulele",
  "Harp ukulele",
  "Lap steelukulele",
  "Pocket ukulele",
  "Resonatorukulele",
  "Soprano ukulele",
  "Tahitianukulele",
  "Tenor ukulele",
  "Baritone ukulele",
  "Bass ukulele",
  "Contrabass ukulele",
  "Cigar box ukulele",
  "Eight-string tenor",
  "Five-string tenor",
  "Lili'u",
  "Six-string tenor",
  "U-bass",
  "Pardessus deviole",
  "Treble viol (dessus)",
  "Alto viol",
  "Bass viol",
  "Division viol",
  "Lyra viol",
  "Tenor viol (taille)",
  "Great bass violone",
  "Contrabass violone",
  "Piccolo violino",
  "Baroque violin",
  "Bass violin",
  "Electric violin",
  "Five string violin",
  "Stroh violin",
  "Tenor violin",
  "Alpine zither (harp zither)",
  "Concert zither",
  "Guitar zither",
  "Overtone zither",
  "AlphaSphere",
  "Audiocubes",
  "Bass pedals",
  "ContinuumFingerboard",
  "Croix Sonore",
  "Denis d'or",
  "Dubreq stylophone",
  "Drum machine",
  "Eigenharp",
  "Electric guitar",
  "Electronic keyboard",
  "Electronicorgan",
  "EWI",
  "Fingerboard synthesizer",
  "Hammond organ",
  "Jammer keyboard",
  "Keyboard",
  "Keytar",
  "Kraakdoos (or cracklebox)",
  "Laser harp",
  "Mellotron",
  "MIDI keyboard",
  "Omnichord",
  "Ondes Martenot",
  "Otamatone",
  "Sampler",
  "Seaboard",
  "Skoog",
  "Synclavier",
  "Synthesizer",
  "Teleharmonium",
  "Tembûr",
  "Tenori-on",
  "Theremin",
  "Turntable",
];
